name: Trigger Jenkins Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
    - run: 
        Set-ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
        Invoke-WebRequest -Uri "http://Sarojini:111877aeebeb61d45b214b7dd4083864b9@localhost:8080/job/Demo/build?token=iamsarojini"    
