name: Trigger Jenkins Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Trigger Jenkins Build
        run: |
          # Define the URI
          $uri = "http://localhost:8080/job/Demo/build?token=iamsarojini"
          
          # Define the username and API token
          $username = "Sarojini"
          $apiToken = "111877aeebeb61d45b214b7dd4083864b9"
          
          # Create a credential object
          $secureApiToken = ConvertTo-SecureString $apiToken -AsPlainText -Force
          $credential = New-Object System.Management.Automation.PSCredential ($username, $secureApiToken)
          
          # Make the request with basic authentication
          Invoke-WebRequest -Uri $uri -Credential $credential
        shell: pwsh
